package adAuctions.algorithms.linearp;
/*
 * Represents a campaign with a number of impressions desired and a value per impression offered.
 *  
 * @author Enrique Areyan
 */
public class Campaign {
	/*
	 * Number of Impressions needed to satisfy this campaign
	 */
    int numImpressions;
    /*
     * Reward generated by this campaign in case it is satisfied.
     */
    double reward;
    /*
     * Constructor
     */
    public Campaign(int numImpressions, double reward){
        this.numImpressions = numImpressions;
        this.reward = reward;
    }
    /*
     * Getters
     */
    public int getNumImpressions(){
    	return this.numImpressions;
    }
    
    public double getReward(){
    	return this.reward;
    }
}
